# Generated by Django 4.2.11 on 2024-04-29 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='it_staff',
            field=models.BooleanField(default=False, verbose_name='IT персонал'),
        ),
        migrations.AddField(
            model_name='user',
            name='supervisor',
            field=models.BooleanField(default=False, verbose_name='Руководитель'),
        ),
    ]
