# Generated by Django 4.2.11 on 2024-04-29 15:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_it_staff_user_supervisor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Наименование')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(verbose_name='Номер контракта')),
                ('object', models.CharField(max_length=150, verbose_name='Наименование объекта')),
                ('state', models.CharField(choices=[('in_process', 'В процессе'), ('restored', 'Восстановлен'), ('contract_organization', 'Организация контракта')], default='in_process', max_length=50, verbose_name='Статус')),
                ('description', models.TextField(verbose_name='Описание работ')),
                ('start', models.DateField(blank=True, null=True, verbose_name='Дата начала работ')),
                ('end', models.DateField(blank=True, null=True, verbose_name='Плановая дата окончания работ')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='Предприятие')),
                ('creator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
                ('gip', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='gip_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Руководитель')),
                ('towm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.town', verbose_name='Город')),
                ('users', models.ManyToManyField(blank=True, null=True, related_name='contracts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователи')),
            ],
            options={
                'verbose_name': 'Контракт',
                'verbose_name_plural': 'Контракты',
            },
        ),
    ]
