# Generated by Django 4.2.11 on 2024-04-29 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_towm_contract_town'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_contracts', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
    ]
