# Generated by Django 4.2.11 on 2024-04-30 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_contract_creator'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserContractFolders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ada', models.BooleanField(default=False)),
                ('mpe', models.BooleanField(default=False)),
                ('mpm', models.BooleanField(default=False)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_folders', to='users.contract', verbose_name='Контракт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contract_folders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Доступы к директориям',
                'verbose_name_plural': 'Доступы к директориям',
            },
        ),
    ]
