# Generated by Django 4.2.11 on 2024-05-01 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_permissionrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissionrequest',
            name='creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_permission_requests', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
    ]
