# Generated by Django 4.2.11 on 2024-05-09 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_permissionrequest_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='ada',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='mpe',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contract',
            name='mpm',
            field=models.BooleanField(default=False),
        ),
    ]
