# Generated by Django 4.2.11 on 2024-05-23 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_contract_ada_contract_mpe_contract_mpm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='company',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.company', verbose_name='Предприятие'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='state',
            field=models.CharField(blank=True, choices=[('in_process', 'В процессе'), ('restored', 'Восстановлен'), ('contract_organization', 'Организация контракта'), ('complete', 'Завершен'), ('arhive', 'Архив')], default='in_process', max_length=50, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='town',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='users.town', verbose_name='Город'),
        ),
    ]
