# Generated by Django 4.2.11 on 2024-05-23 18:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_contract_company_alter_contract_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EndDateContractChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_date', models.DateField(verbose_name='Новая дата')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_date_edits', to='users.contract', verbose_name='Контракт')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_date_edits', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Изменение даты окончания контракта',
                'verbose_name_plural': 'Изменения дат окончания контрактов',
            },
        ),
    ]
